@localHost = localhost
@port = 8080

### Base URLs
@localBaseUrl = http://{{localHost}}:{{port}}


### ==================== /health ====================
GET {{localBaseUrl}}/health


### ==================== /samples ====================
POST {{localBaseUrl}}/samples
Content-Type: application/json

{
    "name": "test1"
}

### ==================== /samples ====================
GET {{localBaseUrl}}/samples


### ==================== /sample ====================
GET {{localBaseUrl}}/samples/test1



