@localHost = localhost
@port = 8080

### Base URLs
@localBaseUrl = http://{{localHost}}:{{port}}


### /
GET {{localBaseUrl}}/


### /images
GET {{localBaseUrl}}/images


### /images/:id
GET {{localBaseUrl}}/images/49


### Create one image with image-file using Prisma Client
POST {{localBaseUrl}}/images
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

My Image Title api.http 2
--boundary
Content-Disposition: form-data; name="file"; filename="sample.png"
Content-Type: image/png

< ./data/sample.png
--boundary--

