venv-activate:
	source myenv/bin/activate

venv-deactivate:
	deactivate	

train:
	python3 iris_training.py --train

convert:
	python3 iris_training.py --convert

predict_versicolor:
	python3 iris_training.py --predict "5.9,3.0,4.2,1.5"

predict_virginica:
	python3 iris_training.py --predict "6.5,3.0,5.2,2.0"

predict_setosa:
	python3 iris_training.py --predict "5.1,3.5,1.4,0.2"

# uvicorn app.main:app --reload
run:
	uvicorn app.main:app --reload