@baseUrl = http://localhost:8000

###################
# Health Check
###################
### Ping Test
GET {{baseUrl}}/ping
Content-Type: application/json

###################
# Microposts API
###################
### Create Micropost
POST {{baseUrl}}/microposts
Content-Type: application/json

{
    "title": "test"
}

### Find All Microposts
GET {{baseUrl}}/microposts
Content-Type: application/json

###################
# Images API
###################
### Create Image
POST {{baseUrl}}/images
Content-Type: application/json

{
    "title": "test",
    "image_url": "https://example.com/test.jpg"
}

### Find All Images
GET {{baseUrl}}/images
Content-Type: application/json
